### ISSUE TITLE
Wrapping __setitem__ in base class, then wrapping __delitem__ in derived class results in NotImplementedError when __setitem__ is called

### ISSUE THREAD

**Issue by dogancan** [google/clif#8] opened 2017-07-01 00:12 UTC
I came across this issue a few days ago. From what I can tell, the code generated for `__delitem__` when wrapping the derived class overrides the code generated for `__setitem__` when wrapping the base class. If `__setitem__` is wrapped in the derived class in addition to the base class, then it works as expected.

**Comment by mrovner** [comment] 2017-07-01 01:11
True. Thanks for reporting. To be fixed in the next release.

**Comment by mrovner** [comment] 2017-07-03 20:15
That is working as intended (eg. same as in pure Python):

getattrofunc PyTypeObject.tp_getattro
This field is inherited by subtypes together with tp_getattr: a subtype inherits both tp_getattr and tp_getattro from its base type when the subtype’s tp_getattr and tp_getattro are both NULL.

setattrofunc PyTypeObject.tp_setattro
This field is inherited by subtypes together with tp_setattr: a subtype inherits both tp_setattr and tp_setattro from its base type when the subtype’s tp_setattr and tp_setattro are both NULL.

**Comment by mrovner** [comment] 2017-07-06 23:55
An 'easy' workaround is to repeat a corresponding 'def' in the derived class.
For example
```
class Base:
  def `get` as __getitem__
  def `set` as __setitem__

class Derived(Base):
  def `set` as __setitem__
  def `del` as __delitem__
```

**Closed** 2017-08-05 00:52 UTC
